version: '3.1'

services:
  api_product:
    restart: always
    container_name: api_product
    build:
      context: .
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /opt/certs:/certs:ro    # Sertifikat HTTPS dimount read-only
    ports:
      - 2360:2345
    networks:
      - shared_network
    env_file:
      - .env

    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearchproduct
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.13.3'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9300:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  esdata:    
   
    