version: '3.1'

services:

  api_product:
    restart: always
    container_name: api_product
    build:
      context: .
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 2360:2345
    depends_on:
      - db
    networks:
      - local

  db:
    container_name: db_product
    image: postgres:14-alpine 
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes: 
      - db_data:/var/lib/postgresql
    ports:
      - "5431:5432"
    networks:
      - local

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.13.3'
    container_name: elasticsearchproduct
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9100:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
    db_data:
    esdata:
      driver: local
networks:
  local:
    driver: bridge
